In [80]:
import time

start_time = time.time()

#### Analyse

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

Import the csv.

In [2]:
df = pd.read_csv('LoanExport.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'LoanExport.csv'

Analyse the shape, how many entries & columns there are.

In [83]:
df.shape

(291451, 28)

Looking at the column names.

In [84]:
df.columns

Index(['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'Channel', 'PPM', 'ProductType', 'PropertyState',
       'PropertyType', 'PostalCode', 'LoanSeqNum', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'SellerName', 'ServicerName',
       'EverDelinquent', 'MonthsDelinquent', 'MonthsInRepayment'],
      dtype='object')

Looking at the datetypes of the columns, and we see that we have some objects, which we have to change into numeric values to use them in the model, otherwise we cant use them at all.

In [85]:
df.dtypes

CreditScore             int64
FirstPaymentDate        int64
FirstTimeHomebuyer     object
MaturityDate            int64
MSA                    object
MIP                     int64
Units                   int64
Occupancy              object
OCLTV                   int64
DTI                     int64
OrigUPB                 int64
LTV                     int64
OrigInterestRate      float64
Channel                object
PPM                    object
ProductType            object
PropertyState          object
PropertyType           object
PostalCode             object
LoanSeqNum             object
LoanPurpose            object
OrigLoanTerm            int64
NumBorrowers           object
SellerName             object
ServicerName           object
EverDelinquent          int64
MonthsDelinquent        int64
MonthsInRepayment       int64
dtype: object

Printing the head of the csv to get some insights.

In [86]:
df.head()

CreditScore  FirstPaymentDate FirstTimeHomebuyer  MaturityDate    MSA  MIP  \
0            0            199902                  N        202901  16974   25   
1            0            199902                  N        202901  19740    0   
2            0            199902                  N        202901  29940    0   
3            0            199902                  N        202901  31084    0   
4            0            199902                  N        202901  35644    0   

   Units Occupancy  OCLTV  DTI  ...  PostalCode    LoanSeqNum  LoanPurpose  \
0      1         O     89   27  ...       60400  F199Q1268030            P   
1      1         O     73   17  ...       80200  F199Q1015092            N   
2      1         O     75   16  ...       66000  F199Q1266886            N   
3      1         O     76   14  ...       90700  F199Q1178167            N   
4      1         O     78   18  ...        7600  F199Q1178517            N   

  OrigLoanTerm NumBorrowers SellerName          ServicerName EverDelinquent  \
0          360            2         FL  WASHINGTONMUTUALBANK              0   
1          360            1         FT  CHASEHOMEFINANCELLC               0   
2          360            2         FL  WASHINGTONMUTUALBANK              0   
3          360            2         GM  GMACMTGECORP                      0   
4          360            2         GM  GMACMTGECORP                      0   

  MonthsDelinquent MonthsInRepayment  
0                0                52  
1                0               144  
2                0                67  
3                0                35  
4                0                54  

[5 rows x 28 columns]

#### Description of each column of our dataset:
    
1 .CreditScore :- Credit score of the client

2.FirstPaymentDate :-The month and year that the first scheduled payment on the loan is due

3.FirstTimeHomebuyer :-The indicator denoting whether a borrower on the loan qualifies as a first-time homebuyer.
“Not Available” will be indicated by 9. 
Y = Yes
N = No
x = Not Available

4.MaturityDate :-The maturity date of the mortgage

5.MSA :-For reperforming, modified fixed-rate and modified step-rate loans, the dollar amount of the loan in the security 
as stated on the note at the time the loans were originated or modified.

6.MIP(Mortgage Insurance Percent MI %):-The percentage of mortgage insurance coverage obtained at origination in effect at the time the security was 
issued.000= No MI
999= Not Available

7.Units:-The number of dwelling units in the mortgaged property at the time the loan was originated. “Not Available” will 
be indicated by 99. 

8.Occupancy:-occupancy status at the time the loan was originated.
P= Primary Residence
S= Second Home
I= Investment Property
9= Not Available

9.OCLTV(outstanding loans at origination by the value of the property. ):-For reperforming, modified fixed-rate and modified step-rate loans, the ratio, expressed as a percentage, 
obtained by dividing the amount of all known outstanding loans at origination by the value of the property.
Property value reflects either the lesser of the sales price or the appraised property value for a purchase, or the 
appraised property value for a refinance.
999 = Not Available

10.DTI(Dept_to_income) :-The ratio obtained by dividing the total monthly debt expense by the total monthly income of the borrower at the time the loan was originated or modified.This number is one way lenders measure your ability to manage the monthly payments to repay the money you plan to borrow.

11.OrigUPB(unpaid principal balance):- For reperforming, modified fixed-rate and modified step-rate loans, the current non-interest bearing unpaid principal balance.

12.LTV (Loan_to_value):- The ratio, expressed as a percentage, obtained by dividing the amount of the loan at origination by the value of  the property(Percentages less than 1% or greater than 998% will be disclosed as “Not Available,” indicated by 999. 
999 = Not Available).The higher your down payment, the lower your LTV ratio. Mortgage lenders may use the LTV in deciding whether to lend to you and to determine if they will require private mortgage insurance

13.OrigInterestRate:- For reperforming, modified fixed-rate and modified step-rate loans, the interest rate of the loan as stated on the 
note at the time the loan was originated.
If value <0 or >25, then the rate is considered not available (securities issued on or after 9/1/2017)

~~14.Channel:-The origination channel used by the party that delivered the loan to the issuer~~

15.PPM :-The indicator denoting whether the borrower is subject to a penalty for early payment of principal.
Y = Yes
N = No

~~16.ProductType (Origination Amortization Type):-For reperforming, modified fixed-rate and modified step-rate loans, the classification of the loan as having either a fixed- or an adjustable-interest rate as stated on the note at the time the loan was originated.~~

~~17.PropertyState :-The abbreviation denoting the location of the property securing the loan.~~

18.PropertyType :;The classification describing the type of property that secures the loan. “Not Available” will be indicated by 99. 
CP = Cooperative
CO = Condominium
PU = Planned Unit Development
SF = Single-Family
MH = Manufactured Housing
99 = Not Available

~~19.PostalCode:-PostalCode of the property.~~

20.LoanSeqNum:- Sequence no. of the loan.

21.LoanPurpose:-The classification describing the purpose of the loan.
C = Refinance - Cash Out
N = Refinance - No Cash Out
R = Refinance - Not Specified
P = Purchase
9 = Not Available
    
22.OrigLoanTerm :-For reperforming, modified fixed-rate and modified step-rate loans, the number of months in which regularly 
scheduled borrower payments are due as stated on the note at the time the loan was originated.

23.NumBorrowers:-The number of borrowers who, at the time the loan was originated, are obligated to repay the loan

~~24.SellerName :-The name of the entity that sold the loan to the issuer. This field will not be updated after issuance, regardless of mergers/acquisitions.~~

~~25.ServicerName :-The name of the entity that services the loan during the current reporting period.~~

26.EverDelinquent:-Identify Delinquent .A mortgage becomes delinquent when the borrower has missed or been late with one or more payments
    0 = Current
    1 = 30-59
    2 = 60-89
    3 = 90-119
    4 = 120+                

27.MonthsDelinquent ( month science last Delinquent ):-For reperforming, modified and modified step-rate loans, the number of months for which a mortgage loan has been reported delinquent.

28.MonthsInRepayment:-Repayment is the act of paying back money previously borrowed from a lende.                                     

Checking if csv has some null-values.

In [87]:
df.isnull().sum()

CreditScore               0
FirstPaymentDate          0
FirstTimeHomebuyer        0
MaturityDate              0
MSA                       0
MIP                       0
Units                     0
Occupancy                 0
OCLTV                     0
DTI                       0
OrigUPB                   0
LTV                       0
OrigInterestRate          0
Channel                   0
PPM                       0
ProductType               0
PropertyState             0
PropertyType              0
PostalCode                0
LoanSeqNum                0
LoanPurpose               0
OrigLoanTerm              0
NumBorrowers              0
SellerName            24994
ServicerName              0
EverDelinquent            0
MonthsDelinquent          0
MonthsInRepayment         0
dtype: int64

As we se 'SellerName' is the only column with null-values, but we dont need it anyways so we drop it.

In [88]:
df.drop(columns=['SellerName'],inplace=True)

Recheck if its gone.

In [89]:
df.isnull().sum()

CreditScore           0
FirstPaymentDate      0
FirstTimeHomebuyer    0
MaturityDate          0
MSA                   0
MIP                   0
Units                 0
Occupancy             0
OCLTV                 0
DTI                   0
OrigUPB               0
LTV                   0
OrigInterestRate      0
Channel               0
PPM                   0
ProductType           0
PropertyState         0
PropertyType          0
PostalCode            0
LoanSeqNum            0
LoanPurpose           0
OrigLoanTerm          0
NumBorrowers          0
ServicerName          0
EverDelinquent        0
MonthsDelinquent      0
MonthsInRepayment     0
dtype: int64

Überprüfung ob es ganze Zeilen gibt die gleich sind, also duplicate.

In [90]:
df.duplicated().sum()

0

Getting insights into the df.

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 27 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         291451 non-null  int64  
 1   FirstPaymentDate    291451 non-null  int64  
 2   FirstTimeHomebuyer  291451 non-null  object 
 3   MaturityDate        291451 non-null  int64  
 4   MSA                 291451 non-null  object 
 5   MIP                 291451 non-null  int64  
 6   Units               291451 non-null  int64  
 7   Occupancy           291451 non-null  object 
 8   OCLTV               291451 non-null  int64  
 9   DTI                 291451 non-null  int64  
 10  OrigUPB             291451 non-null  int64  
 11  LTV                 291451 non-null  int64  
 12  OrigInterestRate    291451 non-null  float64
 13  Channel             291451 non-null  object 
 14  PPM                 291451 non-null  object 
 15  ProductType         291451 non-nul

### Delete non neccesary columns

In [92]:
df.drop(["Channel","ProductType","PropertyState","PostalCode","ServicerName",],axis=1,inplace=True)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         291451 non-null  int64  
 1   FirstPaymentDate    291451 non-null  int64  
 2   FirstTimeHomebuyer  291451 non-null  object 
 3   MaturityDate        291451 non-null  int64  
 4   MSA                 291451 non-null  object 
 5   MIP                 291451 non-null  int64  
 6   Units               291451 non-null  int64  
 7   Occupancy           291451 non-null  object 
 8   OCLTV               291451 non-null  int64  
 9   DTI                 291451 non-null  int64  
 10  OrigUPB             291451 non-null  int64  
 11  LTV                 291451 non-null  int64  
 12  OrigInterestRate    291451 non-null  float64
 13  PPM                 291451 non-null  object 
 14  PropertyType        291451 non-null  object 
 15  LoanSeqNum          291451 non-nul

In [94]:
df.nunique()

CreditScore              370
FirstPaymentDate          66
FirstTimeHomebuyer         3
MaturityDate              96
MSA                      392
MIP                       37
Units                      5
Occupancy                  3
OCLTV                    102
DTI                       66
OrigUPB                  375
LTV                       97
OrigInterestRate         254
PPM                        3
PropertyType               7
LoanSeqNum            291451
LoanPurpose                3
OrigLoanTerm              61
NumBorrowers               3
EverDelinquent             2
MonthsDelinquent         174
MonthsInRepayment        212
dtype: int64

### Delete 'LoanSeqNum' because it has to many different values and its not neccasarry in that case.

In [95]:
df.drop(["LoanSeqNum"],axis=1,inplace=True)

In [96]:
df.nunique()

CreditScore           370
FirstPaymentDate       66
FirstTimeHomebuyer      3
MaturityDate           96
MSA                   392
MIP                    37
Units                   5
Occupancy               3
OCLTV                 102
DTI                    66
OrigUPB               375
LTV                    97
OrigInterestRate      254
PPM                     3
PropertyType            7
LoanPurpose             3
OrigLoanTerm           61
NumBorrowers            3
EverDelinquent          2
MonthsDelinquent      174
MonthsInRepayment     212
dtype: int64

#### Description of each column of our dataset:
    
0.CreditScore :- Credit score of the client

1.FirstPaymentDate :-The month and year that the first scheduled payment on the loan is due

2.FirstTimeHomebuyer :-The indicator denoting whether a borrower on the loan qualifies as a first-time homebuyer.
“Not Available” will be indicated by 9. 
Y = Yes
N = No
x = Not Available

3.MaturityDate :-The maturity date of the mortgage

4.MSA :-For reperforming, modified fixed-rate and modified step-rate loans, the dollar amount of the loan in the security 
as stated on the note at the time the loans were originated or modified.

5.MIP(Mortgage Insurance Percent MI %):-The percentage of mortgage insurance coverage obtained at origination in effect at the time the security was 
issued.000= No MI
999= Not Available

6.Units:-The number of dwelling units in the mortgaged property at the time the loan was originated. “Not Available” will 
be indicated by 99. 

7.Occupancy:-occupancy status at the time the loan was originated.
P= Primary Residence
S= Second Home
I= Investment Property
9= Not Available

8.OCLTV(outstanding loans at origination by the value of the property. ):-For reperforming, modified fixed-rate and modified step-rate loans, the ratio, expressed as a percentage, 
obtained by dividing the amount of all known outstanding loans at origination by the value of the property.
Property value reflects either the lesser of the sales price or the appraised property value for a purchase, or the 
appraised property value for a refinance.
999 = Not Available

9.DTI(Dept_to_income) :-The ratio obtained by dividing the total monthly debt expense by the total monthly income of the borrower at the time the loan was originated or modified.This number is one way lenders measure your ability to manage the monthly payments to repay the money you plan to borrow.

10.OrigUPB(unpaid principal balance):- For reperforming, modified fixed-rate and modified step-rate loans, the current non-interest bearing unpaid principal balance.

11.LTV (Loan_to_value):- The ratio, expressed as a percentage, obtained by dividing the amount of the loan at origination by the value of  the property(Percentages less than 1% or greater than 998% will be disclosed as “Not Available,” indicated by 999. 
999 = Not Available).The higher your down payment, the lower your LTV ratio. Mortgage lenders may use the LTV in deciding whether to lend to you and to determine if they will require private mortgage insurance

12.OrigInterestRate:- For reperforming, modified fixed-rate and modified step-rate loans, the interest rate of the loan as stated on the 
note at the time the loan was originated.
If value <0 or >25, then the rate is considered not available (securities issued on or after 9/1/2017)

13.PPM :-The indicator denoting whether the borrower is subject to a penalty for early payment of principal.
Y = Yes
N = No

14.PropertyType :;The classification describing the type of property that secures the loan. “Not Available” will be indicated by 99. 
CP = Cooperative
CO = Condominium
PU = Planned Unit Development
SF = Single-Family
MH = Manufactured Housing
99 = Not Available

15.LoanPurpose:-The classification describing the purpose of the loan.
C = Refinance - Cash Out
N = Refinance - No Cash Out
R = Refinance - Not Specified
P = Purchase
9 = Not Available
    
16.OrigLoanTerm :-For reperforming, modified fixed-rate and modified step-rate loans, the number of months in which regularly 
scheduled borrower payments are due as stated on the note at the time the loan was originated.

17.NumBorrowers:-The number of borrowers who, at the time the loan was originated, are obligated to repay the loan

18.EverDelinquent:-Identify Delinquent .A mortgage becomes delinquent when the borrower has missed or been late with one or more payments
    0 = Current
    1 = 30-59
    2 = 60-89
    3 = 90-119
    4 = 120+                

19.MonthsDelinquent ( month science last Delinquent ):-For reperforming, modified and modified step-rate loans, the number of months for which a mortgage loan has been reported delinquent.

20.MonthsInRepayment:-Repayment is the act of paying back money previously borrowed from a lende.                                     

### Check Values

We need to check if there are some Values in the df which are set instead of nAn.

In [97]:
for i in df:
        print(df[i].value_counts())
        print('#######################################')

CreditScore
748    2567
734    2537
747    2456
753    2427
764    2419
       ... 
391       1
396       1
445       1
462       1
849       1
Name: count, Length: 370, dtype: int64
#######################################
FirstPaymentDate
199905    104071
199904     91152
199903     89401
199902      2300
199906      2083
           ...  
201111         1
201303         1
200311         1
200403         1
200404         1
Name: count, Length: 66, dtype: int64
#######################################
FirstTimeHomebuyer
N    184154
X     78015
Y     29282
Name: count, dtype: int64
#######################################
MaturityDate
202904    104210
202903     91059
202902     89304
202901      2282
202905      2067
           ...  
202403         1
203304         1
203308         1
203210         1
203202         1
Name: count, Length: 96, dtype: int64
#######################################
MSA
X        39100
31084     9338
16974     8771
12060     6985
47644     6673
         ...  
21

Analyse showed, that there is an 'X' which marks the spot as nAn.

### FirstTimeHomebuyer, MSA, PPM, PropertyType, NumBorrower have 'X' Values, which stands for NaN in this DataSet.

Analysing how many X´s there are.

In [98]:
NaN= {}

for i in list(df.columns):
    if i in ['FirstTimeHomebuyer', 'MSA', 'PPM', 'PropertyType', 'NumBorrowers']:
        X = np.sum(df[i] == "X")
        NaN[i] = X

X = pd.DataFrame.from_dict(NaN, orient = 'index')
print(X)

                        0
FirstTimeHomebuyer  78015
MSA                     0
PPM                  5405
PropertyType            0
NumBorrowers            0


As manually seen ther should be Xses for all of these columns but the code doesnt show it. Das kann daran liegen das die Zeilen nicht gestript werden, also das es vor dem X oder danach leerzeichen gibt die diese unerkannt bleiben lassen.

In [99]:
NaN = {}

for i in list(df.columns):
    if i in ['FirstTimeHomebuyer', 'MSA', 'PPM', 'PropertyType', 'NumBorrowers']:
        X = np.sum(df[i].str.strip() == "X")
        NaN[i] = X

X = pd.DataFrame.from_dict(NaN, orient='index')
print(X)

                        0
FirstTimeHomebuyer  78015
MSA                 39100
PPM                  5405
PropertyType           22
NumBorrowers          339


Hier sind jetzt alle X´e zu sehen.

### Replacing the 'X' Values with the mode of the colums.

#### FirstTimeHomebuyer

In [100]:
df["FirstTimeHomebuyer"].mode()

0    N
Name: FirstTimeHomebuyer, dtype: object

In [101]:
df["FirstTimeHomebuyer"]=df["FirstTimeHomebuyer"].replace(['X'],['N'])

In [102]:
df["FirstTimeHomebuyer"].unique()

array(['N', 'Y'], dtype=object)

#### MSA

In [103]:
df["MSA"].mode()

0    X    
Name: MSA, dtype: object

In [104]:
df["MSA"].dtype

dtype('O')

In [105]:
df["MSA"]=df["MSA"].str.strip().replace(['X'],['0'])

In [106]:
df['MSA']=df['MSA'].astype('int')

In [107]:
round(df["MSA"].median())

29820

In [108]:
df["MSA"]=df["MSA"].replace(0,29820)

In [109]:
df["MSA"].unique()

array([16974, 19740, 29940, 31084, 35644, 29820, 36740, 25540, 48620,
       12060, 12420, 13140, 13644, 15764, 16700, 16940, 17900, 19124,
       20500, 20764, 21340, 22380, 22744, 23060, 23104, 24660, 24860,
       25060, 26900, 27060, 27140, 27260, 28420, 29404, 30780, 31340,
       33124, 33340, 33460, 34820, 35004, 35084, 35380, 37100, 38060,
       38300, 38900, 39300, 39340, 39820, 40060, 40140, 40900, 41180,
       41620, 41700, 41740, 41884, 42044, 42220, 42644, 43900, 46060,
       46700, 47644, 47894, 49180, 49420, 11340, 12100, 14500, 17820,
       17860, 19340, 19804, 28140, 29740, 36084, 36500, 37460, 42060,
       47260, 48424, 12580, 14484, 14860, 19380, 26420, 29420, 29620,
       36540, 37764, 37860, 37964, 38940, 40380, 45300, 19660, 11300,
       11460, 12220, 12940, 13820, 13980, 14740, 15540, 16740, 17140,
       17460, 17780, 22220, 23420, 23844, 24340, 24780, 26180, 27620,
       31420, 31540, 34980, 35300, 39100, 39580, 39900, 40420, 41940,
       41980, 42020,

#### PPM

In [110]:
df["PPM"].mode()

0    N
Name: PPM, dtype: object

In [111]:
df["PPM"]=df["PPM"].replace(['X'],['N'])

In [112]:
df["PPM"].unique()

array(['N', 'Y'], dtype=object)

#### PropertyType

In [113]:
df["PropertyType"].mode()

0    SF
Name: PropertyType, dtype: object

In [114]:
df["PropertyType"]=df["PropertyType"].str.strip().replace(['X'],['SF'])

In [115]:
df["PropertyType"].unique()

array(['SF', 'PU', 'CO', 'MH', 'CP', 'LH'], dtype=object)

#### NumBorrowers

In [116]:
df["NumBorrowers"].mode()

0    2
Name: NumBorrowers, dtype: object

In [117]:
df["NumBorrowers"]=df["NumBorrowers"].str.strip().replace(['X'],[2])

In [118]:
df['NumBorrowers']=df['NumBorrowers'].astype('int')

In [119]:
df["NumBorrowers"].unique()

array([2, 1])

### Checking for 0 values in colums

In [120]:
df.columns

Index(['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'PPM', 'PropertyType', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'EverDelinquent', 'MonthsDelinquent',
       'MonthsInRepayment'],
      dtype='object')

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         291451 non-null  int64  
 1   FirstPaymentDate    291451 non-null  int64  
 2   FirstTimeHomebuyer  291451 non-null  object 
 3   MaturityDate        291451 non-null  int64  
 4   MSA                 291451 non-null  int64  
 5   MIP                 291451 non-null  int64  
 6   Units               291451 non-null  int64  
 7   Occupancy           291451 non-null  object 
 8   OCLTV               291451 non-null  int64  
 9   DTI                 291451 non-null  int64  
 10  OrigUPB             291451 non-null  int64  
 11  LTV                 291451 non-null  int64  
 12  OrigInterestRate    291451 non-null  float64
 13  PPM                 291451 non-null  object 
 14  PropertyType        291451 non-null  object 
 15  LoanPurpose         291451 non-nul

In [122]:
NaN = {}

for i in list(df.columns):
    if i in ['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'PPM', 'PropertyType', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'EverDelinquent', 'MonthsDelinquent',
       'MonthsInRepayment']:
        Y = np.sum(df[i] == 0)
        NaN[i] = Y

Y = pd.DataFrame.from_dict(NaN, orient='index')
print(Y)

                         0
CreditScore           1189
FirstPaymentDate         0
FirstTimeHomebuyer       0
MaturityDate             0
MSA                      0
MIP                 184511
Units                    2
Occupancy                0
OCLTV                    5
DTI                  17796
OrigUPB                  0
LTV                      5
OrigInterestRate         0
PPM                      0
PropertyType             0
LoanPurpose              0
OrigLoanTerm             0
NumBorrowers             0
EverDelinquent      233788
MonthsDelinquent    233788
MonthsInRepayment        0


#### Dopping the entrys which have 0 as value for 'CreditScore'.

In [123]:
df = df[df['CreditScore'] != 0]

In [124]:
NaN = {}

for i in list(df.columns):
    if i in ['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'PPM', 'PropertyType', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'EverDelinquent', 'MonthsDelinquent',
       'MonthsInRepayment']:
        Y = np.sum(df[i] == 0)
        NaN[i] = Y

Y = pd.DataFrame.from_dict(NaN, orient='index')
print(Y)

                         0
CreditScore              0
FirstPaymentDate         0
FirstTimeHomebuyer       0
MaturityDate             0
MSA                      0
MIP                 183881
Units                    2
Occupancy                0
OCLTV                    5
DTI                  17761
OrigUPB                  0
LTV                      5
OrigInterestRate         0
PPM                      0
PropertyType             0
LoanPurpose              0
OrigLoanTerm             0
NumBorrowers             0
EverDelinquent      232924
MonthsDelinquent    232924
MonthsInRepayment        0


#### Replacing the entrys which have 0 as value for 'DTI'.

In [125]:
round(df['DTI'].mean())

30

In [126]:
df["DTI"]=df["DTI"].replace(0,30)

In [127]:
df['DTI'].unique()

array([21, 28, 18, 25, 38, 22, 16, 37, 43, 30, 45, 40, 41, 34, 20, 32, 23,
       19, 49, 27, 24, 29, 33, 50, 35, 56, 31, 14, 64, 39, 42, 17, 13, 15,
       26, 36, 44,  8, 46,  6, 11, 57,  9, 48,  7, 10, 54, 51, 59, 53, 52,
       55, 12,  5,  4, 47, 65, 60, 58,  2,  3, 62,  1, 61, 63])

In [128]:
NaN = {}

for i in list(df.columns):
    if i in ['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'PPM', 'PropertyType', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'EverDelinquent', 'MonthsDelinquent',
       'MonthsInRepayment']:
        Y = np.sum(df[i] == 0)
        NaN[i] = Y

Y = pd.DataFrame.from_dict(NaN, orient='index')
print(Y)

                         0
CreditScore              0
FirstPaymentDate         0
FirstTimeHomebuyer       0
MaturityDate             0
MSA                      0
MIP                 183881
Units                    2
Occupancy                0
OCLTV                    5
DTI                      0
OrigUPB                  0
LTV                      5
OrigInterestRate         0
PPM                      0
PropertyType             0
LoanPurpose              0
OrigLoanTerm             0
NumBorrowers             0
EverDelinquent      232924
MonthsDelinquent    232924
MonthsInRepayment        0


#### Replacing the entrys which have 0 as value for 'LTV'.

In [129]:
df['LTV'].median()

80.0

In [130]:
df["LTV"]=df["LTV"].replace(0,80)

In [131]:
df['LTV'].unique()

array([ 71,  79,  66,  65,  80,  64,  87,  95,  90,  89,  67,  72,  68,
        92,  78,  74,  50,  91,  55,  76,  73,  48,  84,  70,  40,  83,
        85,  57,  97,  93,  28,  56,  82,  75,  69,  94,  45,  52,  30,
        62,  54,  88,  61,  63,  58,  43,  86,  37,  46,  77,  60,  53,
        81,  34,  33,  51,  47, 100,  96,  49,  59,  41,  42,  38,  44,
        25,  36,  98,  31,  32,  29,  35,  27,  26,  24,  39,  13,  10,
        18,  22,  23,  20,  15,  21, 103,  14,  16,  17,  19,   8,  99,
         7,  12,   6,  11,   9])

#### Replacing the entrys which have 0 as value for 'OCLTV'.

In [132]:
df['OCLTV'].median()

80.0

In [133]:
df["OCLTV"]=df["OCLTV"].replace(0,80)

In [134]:
df['OCLTV'].unique()

array([ 71,  79,  66,  65,  80,  64,  87,  95,  90,  89,  67,  72,  68,
        92,  78,  74,  50,  91,  55,  76,  73,  48,  84,  70,  40,  83,
        85,  57,  97,  93,  28,  56,  82,  75,  69,  94,  45,  52,  30,
        62,  54,  88,  61,  63,  58,  43,  86,  37,  46,  77,  60,  53,
        81,  34,  33,  51,  47, 100,  96,  49,  59,  41,  42,  38,  44,
        25,  36,  98,  31,  32,  29,  35,  27,  26,  24,  39, 103,  13,
        10,  18,  22,  23,  20,  15,  21, 102, 101,  14,  16,  17, 105,
        19,   8,  99, 104, 110,   7,  12,   6,  11,   9])

### Dropping entrys with 0 values for 'Units'

In [135]:
df = df[df['Units'] != 0]
df['Units'].unique()

array([1, 2, 3, 4])

In [136]:
NaN = {}

for i in list(df.columns):
    if i in ['CreditScore', 'FirstPaymentDate', 'FirstTimeHomebuyer', 'MaturityDate',
       'MSA', 'MIP', 'Units', 'Occupancy', 'OCLTV', 'DTI', 'OrigUPB', 'LTV',
       'OrigInterestRate', 'PPM', 'PropertyType', 'LoanPurpose',
       'OrigLoanTerm', 'NumBorrowers', 'EverDelinquent', 'MonthsDelinquent',
       'MonthsInRepayment']:
        Y = np.sum(df[i] == 0)
        NaN[i] = Y

Y = pd.DataFrame.from_dict(NaN, orient='index')
print(Y)

                         0
CreditScore              0
FirstPaymentDate         0
FirstTimeHomebuyer       0
MaturityDate             0
MSA                      0
MIP                 183880
Units                    0
Occupancy                0
OCLTV                    0
DTI                      0
OrigUPB                  0
LTV                      0
OrigInterestRate         0
PPM                      0
PropertyType             0
LoanPurpose              0
OrigLoanTerm             0
NumBorrowers             0
EverDelinquent      232923
MonthsDelinquent    232923
MonthsInRepayment        0


## Analysis & Preparation

In [137]:
df.describe(exclude=[object]).T.style.background_gradient(cmap='viridis')

In [138]:
numeric_df = df.select_dtypes(include=[np.number])
numeric_df.corr().T.style.background_gradient(cmap='viridis')


#### New colums

In [139]:
FTH_Mapping = {'Y': 1, 'N': 0}
df['FirstTimeHomebuyer'] = df['FirstTimeHomebuyer'].map(FTH_Mapping)

In [140]:
O_Mapping = {'P': 1, 'S': 2, 'I': 3}
df['Occupancy'] = df['Occupancy'].map(O_Mapping)

In [141]:
PPM_Mapping = {'Y': 1, 'N': 0}
df['PPM'] = df['PPM'].map(PPM_Mapping)

In [142]:
PropertyType_Mapping = {'CP': 1, 'CO': 2, 'PU': 3, 'SF': 4, 'MH': 5}
df['PropertyType'] = df['PropertyType'].map(PropertyType_Mapping)

In [143]:
LoanPurpose_Mapping = {'C': 1, 'N': 2, 'R': 3, 'P': 4}
df['LoanPurpose'] = df['LoanPurpose'].map(LoanPurpose_Mapping)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290260 entries, 1189 to 291450
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         290260 non-null  int64  
 1   FirstPaymentDate    290260 non-null  int64  
 2   FirstTimeHomebuyer  290260 non-null  int64  
 3   MaturityDate        290260 non-null  int64  
 4   MSA                 290260 non-null  int64  
 5   MIP                 290260 non-null  int64  
 6   Units               290260 non-null  int64  
 7   Occupancy           15215 non-null   float64
 8   OCLTV               290260 non-null  int64  
 9   DTI                 290260 non-null  int64  
 10  OrigUPB             290260 non-null  int64  
 11  LTV                 290260 non-null  int64  
 12  OrigInterestRate    290260 non-null  float64
 13  PPM                 290260 non-null  int64  
 14  PropertyType        290155 non-null  float64
 15  LoanPurpose         290260 non-null 

In [145]:
# Identify non-numeric columns
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print("Non-numeric columns:")
print(non_numeric_columns)


Non-numeric columns:
Index([], dtype='object')


In [146]:
df['MonthsInRepayment'].unique()

array([163, 165,  43,  65,  42,  55,  39, 133,  57,   9,  53,  64,  48,
        72, 156,   4,  52,  44,  56,  28,  16,  63,  74,  45,  50,  35,
        17, 211,  34,  60,  24,   5, 212,  36,  19,  62,   7,  58, 183,
        91,  95,  11,  40, 182, 209, 132, 112,  33,  29,  38,  46, 210,
        54,  31,   2,  23,  32, 208,  59,  15,  47,  21, 193, 206,  70,
        14, 148,  77, 169,  25, 136,  49,  22, 135,  37,  41,  26,  66,
       166,  73,  86,  81, 178,  27,  67,  61,  89,   8, 124, 129,  12,
        30, 186,  10,  93,  78,  69, 127,   6, 101,  51, 109,  20,  68,
       121,  94, 168,  18, 189, 130, 194, 190, 103, 158, 177, 198, 143,
       162,  92, 199,  71,  76,  75, 202, 174, 100,  84, 192, 172, 167,
       137, 146, 104,  90, 119,   1, 164,  99, 201, 184, 123, 125, 118,
       120,  80, 111, 139,  13, 205, 141,  96, 144, 116,  79, 149, 105,
       197,  82, 108, 145, 142,  85, 175, 171,  88, 106, 157, 160,  83,
       154,  87, 173, 113, 110, 176, 181, 204, 107, 153,  97, 11

##### Prepayment Spalte

Schwellenwert festlegen, z. B. wenn die Anzahl der MonthsInRepayment kleiner als 30% der gesamten Laufzeit (OrigLoanTerm) ist, setzen wir Prepayment auf 1.

Basierend auf EMI_Remains (die verbleibenden monatlichen Zahlungen) eine Vorfälligkeit identifizieren, wenn z. B. die Restlaufzeit deutlich geringer ist als erwartet.
Dadurch haben wir nun mehr Varianz in der Zielvariable.

In [147]:
df['Prepayment'] = df.apply(lambda row: 0 if row['MonthsInRepayment'] < (0.3 * row['OrigLoanTerm']) else 1, axis=1)

In [148]:
df['Prepayment'].unique()

array([1, 0])

In [149]:
df['Prepayment'].value_counts()

Prepayment
0    250547
1     39713
Name: count, dtype: int64

NaN Werte finden

In [150]:
df.isna().sum()

CreditScore                0
FirstPaymentDate           0
FirstTimeHomebuyer         0
MaturityDate               0
MSA                        0
MIP                        0
Units                      0
Occupancy             275045
OCLTV                      0
DTI                        0
OrigUPB                    0
LTV                        0
OrigInterestRate           0
PPM                        0
PropertyType             105
LoanPurpose                0
OrigLoanTerm               0
NumBorrowers               0
EverDelinquent             0
MonthsDelinquent           0
MonthsInRepayment          0
Prepayment                 0
dtype: int64

NaN Werte mit dem mean value erserten

In [151]:
# Impute missing values using the mode
imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df['PropertyType'] = imp_mode.fit_transform(df[['PropertyType']])
df['Occupancy'] = imp_mode.fit_transform(df[['Occupancy']])

In [152]:
df.isna().sum()

CreditScore           0
FirstPaymentDate      0
FirstTimeHomebuyer    0
MaturityDate          0
MSA                   0
MIP                   0
Units                 0
Occupancy             0
OCLTV                 0
DTI                   0
OrigUPB               0
LTV                   0
OrigInterestRate      0
PPM                   0
PropertyType          0
LoanPurpose           0
OrigLoanTerm          0
NumBorrowers          0
EverDelinquent        0
MonthsDelinquent      0
MonthsInRepayment     0
Prepayment            0
dtype: int64

#### Plot to see which values we have graphically

In [153]:
import matplotlib.pyplot as plt
import seaborn as sns

In [154]:
#numeric_df = df.select_dtypes(include=[np.number])

#num_columns = len(numeric_df.columns)
#nrows = (num_columns // 4) + 1 if num_columns % 4 != 0 else num_columns // 4
#layout = (nrows, 4)

#numeric_df.plot(kind="density", subplots=True, layout=layout, fontsize=8, figsize=(18, 12), sharex=False)
#plt.show() 

#### Description of each column of our dataset:
    
0.CreditScore :- Credit score of the client

1.FirstPaymentDate :-The month and year that the first scheduled payment on the loan is due

2.FirstTimeHomebuyer :-The indicator denoting whether a borrower on the loan qualifies as a first-time homebuyer.
“Not Available” will be indicated by 9. 
1 = Yes
0 = No

3.MaturityDate :-The maturity date of the mortgage

4.MSA :-For reperforming, modified fixed-rate and modified step-rate loans, the dollar amount of the loan in the security 
as stated on the note at the time the loans were originated or modified.

5.MIP(Mortgage Insurance Percent MI %):-The percentage of mortgage insurance coverage obtained at origination in effect at the time the security was 
issued.000= No MI
999= Not Available

6.Units:-The number of dwelling units in the mortgaged property at the time the loan was originated. “Not Available” will 
be indicated by 99. 

7.Occupancy:-occupancy status at the time the loan was originated.
1= Primary Residence
2= Second Home
3= Investment Property

8.OCLTV(outstanding loans at origination by the value of the property. ):-For reperforming, modified fixed-rate and modified step-rate loans, the ratio, expressed as a percentage, 
obtained by dividing the amount of all known outstanding loans at origination by the value of the property.
Property value reflects either the lesser of the sales price or the appraised property value for a purchase, or the 
appraised property value for a refinance.
999 = Not Available

9.DTI(Dept_to_income) :-The ratio obtained by dividing the total monthly debt expense by the total monthly income of the borrower at the time the loan was originated or modified.This number is one way lenders measure your ability to manage the monthly payments to repay the money you plan to borrow.

10.OrigUPB(unpaid principal balance):- For reperforming, modified fixed-rate and modified step-rate loans, the current non-interest bearing unpaid principal balance.

11.LTV (Loan_to_value):- The ratio, expressed as a percentage, obtained by dividing the amount of the loan at origination by the value of  the property(Percentages less than 1% or greater than 998% will be disclosed as “Not Available,” indicated by 999. 
999 = Not Available).The higher your down payment, the lower your LTV ratio. Mortgage lenders may use the LTV in deciding whether to lend to you and to determine if they will require private mortgage insurance

12.OrigInterestRate:- For reperforming, modified fixed-rate and modified step-rate loans, the interest rate of the loan as stated on the 
note at the time the loan was originated.
If value <0 or >25, then the rate is considered not available (securities issued on or after 9/1/2017)

13.PPM :-The indicator denoting whether the borrower is subject to a penalty for early payment of principal.
1 = Yes
0 = No

14.PropertyType :;The classification describing the type of property that secures the loan. “Not Available” will be indicated by 99. 
1 = Cooperative
2 = Condominium
3 = Planned Unit Development
4 = Single-Family
5 = Manufactured Housing
99 = Not Available

15.LoanPurpose:-The classification describing the purpose of the loan.
1 = Refinance - Cash Out
2 = Refinance - No Cash Out
3 = Refinance - Not Specified
4 = Purchase
9 = Not Available
    
16.OrigLoanTerm :-For reperforming, modified fixed-rate and modified step-rate loans, the number of months in which regularly 
scheduled borrower payments are due as stated on the note at the time the loan was originated.

17.NumBorrowers:-The number of borrowers who, at the time the loan was originated, are obligated to repay the loan

18.EverDelinquent:-Identify Delinquent .A mortgage becomes delinquent when the borrower has missed or been late with one or more payments
    0 = Current
    1 = 30-59
    2 = 60-89
    3 = 90-119
    4 = 120+                

19.MonthsDelinquent ( month science last Delinquent ):-For reperforming, modified and modified step-rate loans, the number of months for which a mortgage loan has been reported delinquent.

20.MonthsInRepayment:-Repayment is the act of paying back money previously borrowed from a lende.

21.FirstPayment_Year: Year of FirstPaymentDate.

22.FirstPayment_Month: Month of FirstPaymentDate.

23.MaturityDate_Year: Year of MaturityDate displayed as YYYY.

24.MaturityDate_Month: Month of MaturityDate displayed as MM or M.

25.EMI_Remains: OrigLoanTerm substracted by MonthsInRepayment, displayed in Months.

26.EMI_Remains_Years: EMI_Remains displayed as Years.

27.Current_Year: MaturityDate_Year substacted by EMI_Remains_Years, displayed as YYYY. (Current_Year of loan by substracting EMI_Remains_years from MaturityDate_year)

28.OrigLoanTerm_Year: Tenure in Years of the Loan Term.

29.OrigLoanTerm_Month: Tenure in Months of the Loan Term.

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 290260 entries, 1189 to 291450
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CreditScore         290260 non-null  int64  
 1   FirstPaymentDate    290260 non-null  int64  
 2   FirstTimeHomebuyer  290260 non-null  int64  
 3   MaturityDate        290260 non-null  int64  
 4   MSA                 290260 non-null  int64  
 5   MIP                 290260 non-null  int64  
 6   Units               290260 non-null  int64  
 7   Occupancy           290260 non-null  float64
 8   OCLTV               290260 non-null  int64  
 9   DTI                 290260 non-null  int64  
 10  OrigUPB             290260 non-null  int64  
 11  LTV                 290260 non-null  int64  
 12  OrigInterestRate    290260 non-null  float64
 13  PPM                 290260 non-null  int64  
 14  PropertyType        290260 non-null  float64
 15  LoanPurpose         290260 non-null 

In [156]:
df['PropertyType'].unique()

array([4., 3., 2., 5., 1.])

In [157]:
df.to_csv('LoanExport_New.csv', index=False)

In [158]:
end_time_prep = time.time()

duration_analyse = (end_time_prep - start_time) / 60

print (duration_analyse)

0.06160207986831665
